version: '2'
services:
    web:
        build: ./etc/nginx
        ports:
            - "90:80"
        depends_on:
            - php
            - database
    php:
        build: ./etc/php
        ports:
            - 9000:9000
        links:
            - database:mysqldb
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ${APP_PATH}:/var/www/symfony
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3300:3306
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
    mailcatcher:
        build: ./etc/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - database:db
